/**
 * Provision a Medplum test project and mint client credentials for the
 * integration harness (ADR-0008), then write them to `.env`.
 *
 * Intended for the LOCAL docker-compose Medplum (infra/medplum). It:
 *   1. waits for the server healthcheck,
 *   2. registers a fresh user + project (recaptcha disabled in the dev config),
 *   3. creates a ClientApplication (client-credentials grant),
 *   4. writes MEDPLUM_BASE_URL / MEDPLUM_CLIENT_ID / MEDPLUM_CLIENT_SECRET to `.env`.
 *
 * Usage:
 *   docker compose -f infra/medplum/docker-compose.yml up -d
 *   npm run medplum:provision
 *
 * For a hosted Medplum test project, skip this script and set the three env
 * vars yourself (see docs/architecture/infrastructure.md).
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { MedplumClient, MemoryStorage, resolveId } from "@medplum/core";
import type { ClientApplication } from "@medplum/fhirtypes";

// MedplumClient's PKCE register flow expects a browser `sessionStorage`. In
// Node we back it with Medplum's in-memory storage so the code verifier round-
// trips between startNewUser and processCode.
const globalWithStorage = globalThis as typeof globalThis & {
  sessionStorage?: Storage;
};
globalWithStorage.sessionStorage ??= new MemoryStorage() as unknown as Storage;

const baseUrl = process.env.MEDPLUM_BASE_URL ?? "http://localhost:8103/";
const projectName = process.env.MEDPLUM_PROJECT_NAME ?? "PROM Intake Test";

async function waitForHealthy(url: string, attempts = 60): Promise<void> {
  const healthUrl = new URL("healthcheck", url).toString();
  for (let i = 1; i <= attempts; i++) {
    try {
      const res = await fetch(healthUrl);
      if (res.ok) {
        return;
      }
    } catch {
      // server not up yet
    }
    process.stdout.write(`waiting for Medplum (${i}/${attempts})...\r`);
    await new Promise((r) => setTimeout(r, 2000));
  }
  throw new Error(`Medplum did not become healthy at ${healthUrl}`);
}

async function main(): Promise<void> {
  await waitForHealthy(baseUrl);
  console.log(`\nMedplum healthy at ${baseUrl}`);

  const medplum = new MedplumClient({ baseUrl });

  // Unique per run so re-provisioning never collides on the admin email.
  const suffix = Date.now();
  const email = `harness+${suffix}@example.com`;
  const password = `Test-${suffix}-pw`;

  const newUser = await medplum.startNewUser({
    firstName: "Harness",
    lastName: "Admin",
    email,
    password,
    recaptchaToken: "", // dev config has no recaptcha keys -> validation skipped
  });

  const newProject = await medplum.startNewProject({
    login: newUser.login,
    projectName,
  });

  if (!newProject.code) {
    throw new Error(
      "Project registration did not return an authorization code"
    );
  }
  await medplum.processCode(newProject.code);

  const projectId = resolveId(medplum.getActiveLogin()?.project);
  if (!projectId) {
    throw new Error("Could not resolve the new project id after registration");
  }

  // Create the ClientApplication via the admin endpoint so it also gets its
  // ProjectMembership and a server-minted secret. A plain FHIR create omits the
  // membership, and the client-credentials login is then rejected as an
  // "Invalid client".
  const clientApp = (await medplum.post(`admin/projects/${projectId}/client`, {
    name: "PROM Intake Integration Harness",
    description: "Client-credentials app for integration tests (ADR-0008).",
  })) as ClientApplication;

  if (!clientApp.id || !clientApp.secret) {
    throw new Error("Admin client endpoint did not return an id and secret");
  }

  const envPath = resolve(process.cwd(), ".env");
  const envBody =
    `# Generated by scripts/provision-medplum.ts - local Medplum test project.\n` +
    `# Do not commit. Regenerate any time by re-running \`npm run medplum:provision\`.\n` +
    `MEDPLUM_BASE_URL=${baseUrl}\n` +
    `MEDPLUM_CLIENT_ID=${clientApp.id}\n` +
    `MEDPLUM_CLIENT_SECRET=${clientApp.secret}\n`;
  writeFileSync(envPath, envBody, { encoding: "utf8" });

  console.log(`\nProvisioned project "${projectName}".`);
  console.log(`Wrote credentials to ${envPath}`);
  console.log(`  MEDPLUM_CLIENT_ID=${clientApp.id}`);
  console.log(`\nRun the integration suite with:  npm run test:integration`);
}

main().catch((err) => {
  console.error("\nProvisioning failed:", err);
  process.exit(1);
});
